name: owncloud-app
region: fra
services:
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: bilalakrouch/aidowncloud
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: owncloud
  routes:
  - path: /
  source_dir: /
  dockerfile_path: Dockerfile
  envs:
  - key: OWNCLOUD_DOMAIN
    value: ${APP_DOMAIN}
  - key: OWNCLOUD_TRUSTED_DOMAINS
    value: ${APP_DOMAIN}
  - key: OWNCLOUD_DB_TYPE
    value: mysql
  - key: OWNCLOUD_DB_NAME
    value: ${db.DATABASE}
  - key: OWNCLOUD_DB_USERNAME
    value: ${db.USERNAME}
  - key: OWNCLOUD_DB_PASSWORD
    value: ${db.PASSWORD}
  - key: OWNCLOUD_DB_HOST
    value: ${db.HOSTNAME}
  - key: OWNCLOUD_DB_PORT
    value: ${db.PORT}
  - key: OWNCLOUD_ADMIN_USERNAME
    value: admin
  - key: OWNCLOUD_ADMIN_PASSWORD
    value: AdminPass123!
  - key: OWNCLOUD_MYSQL_UTF8MB4
    value: "true"
  - key: OWNCLOUD_REDIS_ENABLED
    value: "true"
  - key: OWNCLOUD_REDIS_HOST
    value: ${redis.HOSTNAME}
  - key: OWNCLOUD_REDIS_PORT
    value: ${redis.PORT}

databases:
- engine: MYSQL
  name: db
  num_nodes: 1
  size: db-s-1vcpu-1gb
  version: "8"

- engine: REDIS
  name: redis
  num_nodes: 1
  size: db-s-1vcpu-1gb
  version: "7"