name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and push Docker image
        run: |
          echo "Docker image will be built by App Platform"